TT_MAILER_ADDRESS: "smtp.gmail.com"
TT_MAILER_PORT: "587"
TT_MAILER_DOMAIN: "gmail.com"
TT_MAILER_EMAIL: "leave.nascenia@gmail.com"
TT_MAILER_PASSWORD: "qavvyh-wabkym-5mirhE"
TT_CEO_EMAIL: 'istiad@bdipo.com'
